language: go

go:
- 1.13

env:
- GO111MODULE=on

go_import_path: github.com/GoogleCloudPlatform/functions-framework-go

before_script: go mod vendor

script:
- go test -v ./...
- go vet ./...
- find . -not \( \( -wholename './.git' -o -wholename '*/vendor/*' \) -prune \) -name '*.go' | xargs gofmt -s -d
- ./run_http_conformance_test.sh
- ./run_event_conformance_test.sh
- ./run_cloudevent_conformance_test.sh
