go_library(
    name = "funcframework",
    srcs = ["framework.go"],
)

go_test(
    name = "funcframework_test",
    size = "small",
    srcs = ["framework_test.go"],
    library = ":funcframework",
)
